// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "NetOrchestrator Team",
            "url": "https://github.com/your-org/netorchestrator",
            "email": "support@netorchestrator.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Check API health status and connectivity to all dependencies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "healthy"
                                },
                                "timestamp": {
                                    "type": "string",
                                    "example": "2024-01-01T12:00:00Z"
                                },
                                "version": {
                                    "type": "string",
                                    "example": "1.0.0"
                                },
                                "dependencies": {
                                    "type": "object",
                                    "properties": {
                                        "database": {
                                            "type": "string",
                                            "example": "connected"
                                        },
                                        "redis": {
                                            "type": "string",
                                            "example": "connected"
                                        },
                                        "influxdb": {
                                            "type": "string",
                                            "example": "connected"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "unhealthy"
                                },
                                "error": {
                                    "type": "string",
                                    "example": "Database connection failed"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/networks": {
            "get": {
                "description": "Retrieve all networks with optional filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networks"
                ],
                "summary": "List all networks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer", 
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by network status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "networks": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "integer",
                                                "example": 1
                                            },
                                            "name": {
                                                "type": "string",
                                                "example": "Production Network"
                                            },
                                            "description": {
                                                "type": "string",
                                                "example": "Main production network infrastructure"
                                            },
                                            "type": {
                                                "type": "string",
                                                "example": "vpc"
                                            },
                                            "status": {
                                                "type": "string",
                                                "example": "active"
                                            },
                                            "created_at": {
                                                "type": "string",
                                                "example": "2024-01-01T12:00:00Z"
                                            },
                                            "updated_at": {
                                                "type": "string",
                                                "example": "2024-01-01T12:00:00Z"
                                            }
                                        }
                                    }
                                },
                                "total": {
                                    "type": "integer",
                                    "example": 100
                                },
                                "page": {
                                    "type": "integer", 
                                    "example": 1
                                },
                                "limit": {
                                    "type": "integer",
                                    "example": 20
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "example": "Failed to retrieve networks"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new network with specified configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networks"
                ],
                "summary": "Create a new network",
                "parameters": [
                    {
                        "description": "Network configuration", 
                        "name": "network",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name", "type"],
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "example": "Development Network"
                                },
                                "description": {
                                    "type": "string",
                                    "example": "Network for development environment"
                                },
                                "type": {
                                    "type": "string",
                                    "example": "vpc"
                                },
                                "cidr": {
                                    "type": "string",
                                    "example": "10.0.0.0/16"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "example": 123
                                },
                                "name": {
                                    "type": "string",
                                    "example": "Development Network"
                                },
                                "status": {
                                    "type": "string",
                                    "example": "active"
                                },
                                "created_at": {
                                    "type": "string",
                                    "example": "2024-01-01T12:00:00Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "example": "Invalid network configuration"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "NetOrchestrator API",
	Description:      "Enterprise Network-as-a-Service (NaaS) automation platform providing comprehensive network orchestration, monitoring, and management capabilities.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}